- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: install apache server from debian family
      command: apt-get -y install apache2
      when: ansible_os_family == "Debian"
    - name: install apache server from redhat family
      command: yum -y install httpd
      when: ansible_os_family == "RedHat"
